### ISSUE TITLE
Doubts on "Integrity Checking and Lock Files" Article

### ISSUE THREAD

**Issue by pols63** [denoland/deno-docs#97]
Greetings!

The article "Integrity Checking and Lock Files" doesn't explain what happen if the checking fails. How the another developer fix the problem? The dependency on cloud has not the code that the project needs. Must the first developer share the dependency manually? How do that?

Thanks. Deno is great!

**Comment by hashrock** [comment]
Thank you! If the check fails, the program won't run. While you can commit only the file hash by including `deno.lock`, if the check fails, another developer will need to delete `deno.lock`. Additionally, external URLs are expected to be immutable. To avoid potential issues, it's advised to host on deno.land/x since it guarantees immutability.
